name: Déployer sur GitHub Pages

on:
  # Déclenchez le workflow à chaque fois que vous poussez vers la branche `main`
  # Vous utilisez un nom de branche différent ? Remplacez `main` par le nom de votre branche.
  push:
    branches: [ main ]
  # Vous permet d'exécuter ce workflow manuellement à partir de l'onglet Actions sur GitHub.
  workflow_dispatch:

# Autoriser cette tâche à cloner le dépôt et à créer un déploiement de page
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Extraire votre dépôt à l'aide de git
        uses: actions/checkout@v5
      - name: Installer, compiler et télécharger votre site
        uses: withastro/action@v5
        # with:
          # path: . # L'emplacement racine de votre projet Astro dans le dépôt. (facultatif)
          # node-version: 24 # Version spécifique de Node à utiliser pour compiler votre site. La valeur par défaut est 22. (facultatif)
          # package-manager: pnpm@latest # Gestionnaire de paquets Node à utiliser pour installer les dépendances et compiler votre site. Détecté automatiquement en fonction de votre fichier de verrouillage. (facultatif)
          # build-cmd: pnpm run build # La commande à exécuter pour compiler votre site. Exécute par défaut le script/la tâche de compilation du paquet. (facultatif)
        # env:
          # PUBLIC_POKEAPI: 'https://pokeapi.co/api/v2' # Utilisez des guillemets simples pour la valeur de la variable. (facultatif)

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Déployer sur GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4